public class Main {
    public static void main(String[] args) {
        System.out.println("    Решение Задачи-1");
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("    Решение Задачи-2");
        dog = dog + 4;
        cat = cat + 4;
        paper = paper + 4;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("    Решение Задачи-3");
        dog = dog - 3.5;
        cat = cat - 1.6;
        paper = paper - 7639;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("    Решение Задачи-4");
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        System.out.println("    Решение Задачи-5");
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        System.out.println("    Решение Задачи-6");
        var boxer1 = 78.2;
        var boxer2 = 82.7;
        var boxerSum = 0.0;
        var boxerRaz = 0.0;
        boxerSum = boxer1 + boxer2;
        System.out.println("Общий вес бойцов"+boxerSum+"kg.");
        boxerRaz = boxer1 - boxer2;
        System.out.println("Разница а весе бойцов"+boxerRaz+"kg.");
        System.out.println("    Решение Задачи-7");
        var boxerRaz1 = 0.0;
        var boxerOst = 0.0;
        boxerRaz1 = boxer2 - boxer1;
        System.out.println("Разница а весе бойцов(вычитанием): "+boxerRaz1+"kg.");
        boxerOst = boxer2 % boxer1;
        System.out.println("Разница а весе бойцов(остатком от деления): "+boxerOst+"kg.");
        System.out.println("    Решение Задачи-8");
        var hoursWork = 640;
        var hourWork = 8;
        var rabotnikov = 0;
        rabotnikov = hoursWork / hourWork;
        System.out.println("Всего работников в компании- "+rabotnikov+" человек.");
        var vsegoRabot = rabotnikov + 94;
        hoursWork = hourWork * vsegoRabot;
        System.out.println("Если в компании работает "+vsegoRabot+" человек, то всего "+hoursWork+" часов может быть поделено между сотрудниками.");}
}